import React,{useEffect,useState,useCallback}from'react';
import{NavLink,useNavigate}from'react-router-dom';
import{LogOut,LayoutDashboard,CalendarDays,Users,FileText,AlertTriangle,MessageSquare,ClipboardList,Clock,DoorOpen,Activity,UsersRound,BookOpen,BarChart3,StickyNote,Bell,User,KeyRound,Settings,ShieldCheck,Menu,X,Building2}from'lucide-react';
import{supabase}from'../services/supabase';import{currentProfile}from'../services/data';import SiteFooter from'./SiteFooter';
const counselorItems=[['/weekly-program','البرنامج اليومي/الأسبوعي',CalendarDays],['/dashboard','ملخص أعمالي',LayoutDashboard],['/students','الطلاب',Users],['/cases','دراسة الحالات',FileText],['/hot-cases','الحالات الساخنة',AlertTriangle],['/interviews','المقابلات والاستشارات',MessageSquare],['/absence','الغياب',ClipboardList],['/lateness','التأخر الصباحي',Clock],['/dropout','التسرب',DoorOpen],['/activities','الأنشطة',Activity],['/group-counseling','الإرشاد الجمعي',UsersRound],['/guidance','الإرشاد التوجيهي',BookOpen],['/annual-plan','الخطة السنوية',BarChart3],['/reports','التقارير',BarChart3],['/notes','دفتر الملاحظات',StickyNote],['/notifications','الإشعارات',Bell],['/messages','المراسلات',MessageSquare],['/profile','البيانات الشخصية',User],['/change-password','تغيير كلمة المرور',KeyRound],['/settings','الإعدادات',Settings]];
const managerItems=[['/directorate-dashboard','الإحصائيات والمتابعة',BarChart3],['/directorates','المديريات',Building2],['/schools','المدارس',Building2],['/administration','إدارة الموظفين',UsersRound],['/messages','مراسلات الموظفين',MessageSquare],['/notifications','الإشعارات',Bell],['/profile','البيانات الشخصية',User],['/change-password','تغيير كلمة المرور',KeyRound],['/settings','الإعدادات',Settings]];
const labels={MINISTRY:'مسؤول الإرشاد',DIRECTORATE:'رئيس القسم',PRINCIPAL:'المشرف التربوي',COUNSELOR:'المرشد التربوي'};
function clickSound(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=520;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.025,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.075);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch{}}
function messageSound(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C();[660,880].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,c.currentTime+i*.09);g.gain.exponentialRampToValueAtTime(.035,c.currentTime+i*.09+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+i*.09+.08);o.connect(g);g.connect(c.destination);o.start(c.currentTime+i*.09);o.stop(c.currentTime+i*.09+.085)})}catch{}}
export default function AppLayout({children}){const nav=useNavigate();const[open,setOpen]=useState(false);const[profile,setProfile]=useState(null);useEffect(()=>{currentProfile().then(setProfile).catch(()=>{})},[]);useEffect(()=>{if(!profile?.id)return;let channel;try{channel=supabase?.channel('incoming-messages-'+profile.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'recipient_id=eq.'+profile.id},()=>messageSound()).subscribe()}catch{}return()=>{try{if(channel)supabase.removeChannel(channel)}catch{}}},[profile?.id]);const logout=async()=>{await supabase?.auth.signOut();nav('/login')};const supervisory=['MINISTRY','DIRECTORATE','PRINCIPAL'].includes(profile?.role);const items=supervisory?managerItems:counselorItems;const handleNav=useCallback(()=>{clickSound();setOpen(false)},[]);return <div className="shell"><button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="فتح القائمة"><Menu size={21}/></button><aside className={open?'open':''}><div className="brand"><div className="brand-mark"><ShieldCheck size={22}/></div><div><h2>{labels[profile?.role]||'نظام الإرشاد'}</h2><small>إدارة ومتابعة الإرشاد التربوي</small></div><button className="close-menu" onClick={()=>setOpen(false)}><X size={19}/></button></div>{profile&&<div className="profile-mini"><div className="avatar">{(profile.full_name||'م').slice(0,1)}</div><div><strong>{profile.full_name}</strong><small>{labels[profile.role]}{profile.directorates?.name?` • ${profile.directorates.name}`:''}{profile.schools?.name?` • ${profile.schools.name}`:''}</small></div></div>}<nav>{items.map(([p,t,I])=><NavLink key={p} to={p} onClick={handleNav} className={({isActive})=>isActive?'active':''}><I size={17}/><span>{t}</span></NavLink>)}</nav><div className="side-footer"><div className="security-chip"><ShieldCheck size={15}/><span>حماية البيانات مفعلة</span></div><button className="logout" onClick={logout}><LogOut size={17}/> تسجيل الخروج</button></div></aside><main>{children}<SiteFooter/></main></div>}
