import React,{useEffect,useState}from'react'
import{useNavigate,useSearchParams}from'react-router-dom'
import{Page,Card,Input,Textarea,Button,Select,ErrorNotice}from'../components/UI'
import{currentProfile,listActiveAcademicData,createActivityRecord,getActivityRecord,updateActivityRecord,updateWeeklyItem}from'../services/data'
import{Save,ArrowRight}from'lucide-react'

const pad=n=>String(n).padStart(2,'0')
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
const dayName=date=>{const d=new Date(`${date}T00:00:00`);return ['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'][d.getDay()]||''}
const activityTypes=[
 ['VISIT','زيارة'],['NEWSLETTER','نشرة'],['RADIO','إذاعة'],['SEMINAR','ندوة'],['LECTURE','محاضرة'],['WORKSHOP','ورشة عمل'],['WALL_MAGAZINE','مجلة حائط'],['OTHER','أخرى']
]

export default function Activities(){
 const nav=useNavigate();const[params]=useSearchParams();
 const recordId=params.get('record_id'),weeklyItemId=params.get('weekly_item_id'),weeklyDate=params.get('date')||today(),weeklyPeriod=params.get('period')||'الحصة الأولى';
 const selectedWorkType=params.get('work_type')||'نشاط إرشادي';
 const[academic,setAcademic]=useState({years:[],semesters:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const[form,setForm]=useState({activity_type:'OTHER',activity_date:weeklyDate,target_group:'',title:'',objectives:'',description:'',results:'',recommendations:'',notes:'',school_year_id:params.get('year_id')||'',semester_id:params.get('semester_id')||''})
 useEffect(()=>{(async()=>{try{const[a,p]=await Promise.all([listActiveAcademicData(),currentProfile()]);setAcademic(a);setForm(f=>({...f,school_year_id:f.school_year_id||a.years?.[0]?.id||'',semester_id:f.semester_id||a.semesters?.find(x=>!f.school_year_id||x.school_year_id===f.school_year_id)?.id||''}));if(recordId){const r=await getActivityRecord(recordId);setForm(f=>({...f,...r,description:r.description||''}))}}catch(e){setError(e.message||'تعذر تحميل النموذج.')}finally{setLoading(false)}})()},[recordId])
 const save=async()=>{if(!form.activity_date||!form.title.trim())return setError('أدخل التاريخ وموضوع النشاط.');if(!form.school_year_id||!form.semester_id)return setError('اختر السنة الدراسية والفصل.');setSaving(true);setError('');try{const payload={activity_type:form.activity_type,activity_date:form.activity_date,title:form.title.trim(),target_group:form.target_group||'',participant_count:null,location:'',objectives:form.objectives||'',results:form.results||'',recommendations:form.recommendations||'',notes:`${form.description||''}${form.notes?'\n'+form.notes:''}`.trim(),school_year_id:form.school_year_id,semester_id:form.semester_id};const r=recordId?await updateActivityRecord(recordId,payload):await createActivityRecord(payload);if(weeklyItemId)await updateWeeklyItem(weeklyItemId,{work_record_id:r.id,work_route:'/activities',work_label:selectedWorkType||'نشاط إرشادي',topic:form.title.trim(),activity_type:selectedWorkType||'نشاط إرشادي',work_saved_at:new Date().toISOString()});nav('/weekly-program')}catch(e){setError(e.message||'تعذر حفظ النموذج.')}finally{setSaving(false)}}
 return <Page title="الأنشطة" sub="تعبئة نموذج النشاط المرتبط بالحصة ثم حفظه وتوثيقه.">{error&&<ErrorNotice>{error}</ErrorNotice>}{loading?<div className="loading">جارٍ تحميل النموذج...</div>:<Card><div className="section-title"><div><h2>{recordId?'تعديل نموذج النشاط':'نموذج النشاط'}</h2><span>الحصة: {weeklyPeriod} — التاريخ: {weeklyDate}</span><div className="selected-work-type">نوع العمل المحدد من البرنامج: <strong>{selectedWorkType}</strong></div></div></div><div className="form-grid two"><Select label="نوع النشاط" value={form.activity_type} onChange={e=>setForm({...form,activity_type:e.target.value})}>{activityTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Input label="التاريخ" type="date" value={form.activity_date} onChange={e=>setForm({...form,activity_date:e.target.value})}/></div><div className="form-grid two"><Input label="الفئة المستهدفة" value={form.target_group} onChange={e=>setForm({...form,target_group:e.target.value})}/><Input label="الموضوع" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="form-grid two"><Select label="السنة الدراسية" value={form.school_year_id} onChange={e=>setForm({...form,school_year_id:e.target.value,semester_id:''})}><option value="">اختر</option>{academic.years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</Select><Select label="الفصل الدراسي" value={form.semester_id} onChange={e=>setForm({...form,semester_id:e.target.value})}><option value="">اختر</option>{academic.semesters.filter(s=>!form.school_year_id||s.school_year_id===form.school_year_id).map(s=><option key={s.id} value={s.id}>{s.type==='SECOND'?'الثاني':'الأول'}</option>)}</Select></div><Textarea label="الأهداف" value={form.objectives} onChange={e=>setForm({...form,objectives:e.target.value})}/><Textarea label="الوصف" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Textarea label="النتائج" value={form.results} onChange={e=>setForm({...form,results:e.target.value})}/><Textarea label="ملاحظات إضافية" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><div className="row-actions"><Button loading={saving} onClick={save}><Save size={16}/> حفظ النموذج</Button><Button variant="secondary" onClick={()=>nav('/weekly-program')}><ArrowRight size={16}/> العودة للبرنامج الأسبوعي</Button></div></Card>}</Page>
}

