import React,{useEffect,useState}from'react'
import{Page,Card,Button,ErrorNotice,Select}from'../components/UI'
import{dashboardStats,currentProfile,listWeeklyPrograms,listActiveAcademicData}from'../services/data'
import{CalendarDays,Users,FileText,AlertTriangle,ArrowLeft,RefreshCw}from'lucide-react'
import{Link}from'react-router-dom'
const semesterLabel=s=>{const t=`${s?.type||''} ${s?.name||''}`.toUpperCase();return t.includes('SECOND')||t.includes('2')||s?.name?.includes('الثاني')?'الثاني':'الأول'}
const yearLabel=y=>y?.name||''
export default function Dashboard(){
 const[stats,setStats]=useState({students:0,cases:0,hotCases:0,activities:0}),[profile,setProfile]=useState(null),[program,setProgram]=useState(null),[academic,setAcademic]=useState({years:[],semesters:[]}),[yearId,setYearId]=useState(''),[semesterId,setSemesterId]=useState(''),[error,setError]=useState('')
 const load=async()=>{try{const[a,pr]=await Promise.all([listActiveAcademicData(),currentProfile()]);setAcademic(a);setProfile(pr);setYearId(y=>y||a.years?.find(x=>x.is_active)?.id||a.years?.[0]?.id||'');setSemesterId(s=>s||a.semesters?.find(x=>x.type==='FIRST')?.id||a.semesters?.[0]?.id||'')}catch(e){setError(e.message||'تعذر تحميل الملخص.')}}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(!yearId)return;const s=academic.semesters?.find(x=>x.id===semesterId&&x.school_year_id===yearId);if(!s)setSemesterId(academic.semesters?.find(x=>x.school_year_id===yearId&&x.type==='FIRST')?.id||'')},[yearId,academic.semesters,semesterId])
 useEffect(()=>{if(!yearId||!semesterId)return;(async()=>{try{const[s,p]=await Promise.all([dashboardStats(yearId,semesterId),listWeeklyPrograms()]);setStats(s);setProgram(p.find(x=>x.school_year_id===yearId&&x.semester_id===semesterId)||null)}catch(e){setError(e.message||'تعذر تحميل الملخص.')}})()},[yearId,semesterId])
 return <Page title={`أهلًا بك، المرشد التربوي ${profile?.full_name||''} 🌿`} sub={`${profile?.directorates?.name||'المديرية غير محددة'} • ${profile?.schools?.name||'المدرسة غير محددة'} • ملخص أعمالك حسب السنة والفصل`} actions={<Button variant="secondary" onClick={load}><RefreshCw size={16}/> تحديث</Button>}>
  {error&&<ErrorNotice>{error}</ErrorNotice>}
  <Card><div className="form-grid two"><Select label="السنة الدراسية" value={yearId} onChange={e=>setYearId(e.target.value)}><option value="">اختر السنة</option>{academic.years.map(y=><option key={y.id} value={y.id}>{yearLabel(y)}</option>)}</Select><Select label="الفصل الدراسي" value={semesterId} onChange={e=>setSemesterId(e.target.value)}><option value="">اختر الفصل</option>{academic.semesters.filter(s=>!yearId||s.school_year_id===yearId).map(s=><option key={s.id} value={s.id}>{semesterLabel(s)}</option>)}</Select></div></Card>
  <div className="hero-card"><div><span>لوحة المتابعة</span><h2>كل ملفاتك الإرشادية في مكان واحد</h2><p>الإحصائيات والبرنامج الحالي مرتبطان بالسنة الدراسية والفصل المحددين.</p></div><Link to="/weekly-program" className="hero-action">فتح البرنامج الأسبوعي <ArrowLeft size={17}/></Link></div>
  <div className="grid stats-grid"><Card className="stat-card"><div className="stat-icon"><Users size={19}/></div><span className="stat-label">الطلاب المسندون</span><div className="stat">{stats.students}</div></Card><Card className="stat-card"><div className="stat-icon"><FileText size={19}/></div><span className="stat-label">دراسات الحالات</span><div className="stat">{stats.cases}</div></Card><Card className="stat-card"><div className="stat-icon"><AlertTriangle size={19}/></div><span className="stat-label">الحالات الساخنة المفتوحة</span><div className="stat">{stats.hotCases}</div></Card><Card className="stat-card"><div className="stat-icon"><CalendarDays size={19}/></div><span className="stat-label">الأنشطة المسجلة</span><div className="stat">{stats.activities}</div></Card></div>
  <div className="dashboard-grid"><Card><div className="section-title"><div><h2>البرنامج الحالي</h2><span>البرنامج المرتبط بالسنة والفصل المحددين</span></div><Link to="/weekly-program">عرض الكل</Link></div>{program?<div className="program-summary"><strong>{program.title||'برنامج أسبوعي'}</strong><span>{program.week_start} — {program.week_end}</span><div className="mini-count">{program.weekly_program_items?.length||0} بند مسجل</div></div>:<div className="empty"><div className="empty-icon">☀</div><strong>لا يوجد برنامج محفوظ لهذا الفصل</strong><span>ابدأ بتسجيل أعمال الأسبوع الحالي.</span><Link className="btn" to="/weekly-program">إنشاء البرنامج</Link></div>}</Card><Card><div className="section-title"><div><h2>اختصارات</h2><span>الوصول السريع للمهام المتكررة</span></div></div><div className="quick-grid"><Link to="/students">👩‍🎓 الطلاب</Link><Link to="/cases">📋 دراسة حالة</Link><Link to="/hot-cases">⚠️ حالة ساخنة</Link><Link to="/notes">📝 ملاحظات</Link><Link to="/reports">📊 التقارير</Link><Link to="/annual-plan">🎯 الخطة السنوية</Link></div></Card></div>
 </Page>
}