import React,{useEffect,useState}from'react'
import{useNavigate,useSearchParams}from'react-router-dom'
import{Page,Card,Input,Textarea,Button,Select,ErrorNotice}from'../components/UI'
import{currentProfile,listActiveAcademicData,createGroupCounselingRecord,getGroupCounselingRecord,updateGroupCounselingRecord,createWeeklyItem,updateWeeklyItem}from'../services/data'
import{ArrowRight,Save}from'lucide-react'
const days=['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس'];const dayName=date=>{const d=new Date(`${date}T00:00:00`);return days[d.getDay()]||''};const pad=n=>String(n).padStart(2,'0');const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};const yearLabel=y=>y?.name||`${new Date(y.start_date).getFullYear()}/${new Date(y.end_date).getFullYear()}`;const semesterLabel=s=>{const t=`${s?.type||''} ${s?.name||''}`.toUpperCase();return t.includes('SECOND')||t.includes('2')||s?.name?.includes('الثاني')?'الثاني':'الأول'}
export default function GroupCounseling(){
 const nav=useNavigate();const[params]=useSearchParams();const selectedWorkType=params.get('work_type')||'جلسة جمعي';const recordId=params.get('record_id'),weeklyItemId=params.get('weekly_item_id'),weeklyProgramId=params.get('weekly_program_id'),weeklyDate=params.get('date')||today(),weeklyPeriod=params.get('period')||'الحصة الأولى';const[academic,setAcademic]=useState({years:[],semesters:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');const[form,setForm]=useState({name:'',problem:'',member_count:'',session_date:weeklyDate,location:'',topic:'',objectives:'',outputs:'',recommendations:'',notes:'',school_year_id:params.get('year_id')||'',semester_id:params.get('semester_id')||''})
 useEffect(()=>{(async()=>{try{const a=await listActiveAcademicData();setAcademic(a);setForm(f=>({...f,school_year_id:f.school_year_id||a.years?.[0]?.id||'',semester_id:f.semester_id||a.semesters?.find(x=>!f.school_year_id||x.school_year_id===f.school_year_id)?.id||''}));if(recordId){const r=await getGroupCounselingRecord(recordId);setForm(f=>({...f,...r,session_date:r.session?.session_date||f.session_date,location:r.session?.location||'',topic:r.session?.topic||'',outputs:r.session?.outputs||'',notes:r.session?.notes||''}))}}catch(e){setError(e.message||'تعذر تحميل الملف.')}finally{setLoading(false)}})()},[recordId])
 const save=async()=>{if(!form.name.trim()||!form.session_date)return setError('أدخل اسم المجموعة والتاريخ.');if(!form.school_year_id||!form.semester_id)return setError('اختر السنة الدراسية والفصل.');setSaving(true);setError('');try{const payload={name:form.name.trim(),problem:form.problem||'',member_count:form.member_count?Number(form.member_count):null,target_group:'',objectives:form.objectives||'',recommendations:form.recommendations||'',school_year_id:form.school_year_id,semester_id:form.semester_id,session:{session_date:form.session_date,location:form.location||'',topic:form.topic||'',objectives:form.objectives||'',activities:'',outputs:form.outputs||'',notes:form.notes||'',next_topic:''}};const r=recordId?await updateGroupCounselingRecord(recordId,payload):await createGroupCounselingRecord(payload);if(weeklyItemId)await updateWeeklyItem(weeklyItemId,{work_record_id:r.id,work_route:'/group-counseling',work_label:'الإرشاد الجمعي',topic:'الإرشاد الجمعي',activity_type:'جلسة جمعي'});else if(weeklyProgramId)await createWeeklyItem({weekly_program_id:weeklyProgramId,day_date:weeklyDate,period:weeklyPeriod,day_name:dayName(weeklyDate),activity_type:'جلسة جمعي',topic:'الإرشاد الجمعي',objectives:'',notes:'',status:'COMPLETED',work_record_id:r.id,work_route:'/group-counseling',work_label:'الإرشاد الجمعي',work_saved_at:new Date().toISOString()});nav('/weekly-program')}catch(e){setError(e.message||'تعذر حفظ الملف.')}finally{setSaving(false)}}
 return <Page title="الإرشاد الجمعي" sub="إدخال بيانات المجموعة والجلسة وربطها بخانة العمل في البرنامج الأسبوعي.">{error&&<ErrorNotice>{error}</ErrorNotice>}{loading?<div className="loading">جارٍ تحميل الملف...</div>:<Card><div className="section-title"><div><h2>{recordId?'تعديل الإرشاد الجمعي':'بيانات الإرشاد الجمعي'}</h2><span>السنة والفصل مرتبطان بهذا السجل.</span><div className="selected-work-type">نوع العمل المحدد من البرنامج: <strong>{selectedWorkType}</strong></div></div></div><div className="form-grid two"><Select label="السنة الدراسية" value={form.school_year_id} onChange={e=>setForm({...form,school_year_id:e.target.value})}><option value="">اختر</option>{academic.years.map(y=><option key={y.id} value={y.id}>{yearLabel(y)}</option>)}</Select><Select label="الفصل الدراسي" value={form.semester_id} onChange={e=>setForm({...form,semester_id:e.target.value})}><option value="">اختر</option>{academic.semesters.filter(s=>!form.school_year_id||s.school_year_id===form.school_year_id).map(s=><option key={s.id} value={s.id}>{semesterLabel(s)}</option>)}</Select><Input label="اسم المجموعة" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input label="المشكلة" value={form.problem||''} onChange={e=>setForm({...form,problem:e.target.value})}/><Input label="عدد الأعضاء" type="number" min="0" value={form.member_count||''} onChange={e=>setForm({...form,member_count:e.target.value})}/><Input label="التاريخ" type="date" value={form.session_date} onChange={e=>setForm({...form,session_date:e.target.value})}/><Input label="المكان" value={form.location||''} onChange={e=>setForm({...form,location:e.target.value})}/><Input label="موضوع الجلسة" value={form.topic||''} onChange={e=>setForm({...form,topic:e.target.value})}/></div><div className="form-grid two"><Textarea label="الأهداف" value={form.objectives||''} onChange={e=>setForm({...form,objectives:e.target.value})}/><Textarea label="المخرجات" value={form.outputs||''} onChange={e=>setForm({...form,outputs:e.target.value})}/><Textarea label="التوصيات" value={form.recommendations||''} onChange={e=>setForm({...form,recommendations:e.target.value})}/><Textarea label="ملاحظات إضافية" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></div><Button loading={saving} onClick={save}><Save size={16}/> حفظ البيانات</Button></Card>}</Page>
}

