import React,{useEffect,useState}from'react'
import{useNavigate,useSearchParams}from'react-router-dom'
import{Page,Card,Input,Textarea,Button,Select,ErrorNotice}from'../components/UI'
import{currentProfile,listActiveAcademicData,listSectionsBySchool,createGuidanceRecord,getGuidanceRecord,updateGuidanceRecord,createWeeklyItem,updateWeeklyItem}from'../services/data'
import{ArrowRight,Save}from'lucide-react'
const days=['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس'];const dayName=date=>{const d=new Date(`${date}T00:00:00`);return days[d.getDay()]||''};const pad=n=>String(n).padStart(2,'0');const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};const yearLabel=y=>y?.name||`${new Date(y.start_date).getFullYear()}/${new Date(y.end_date).getFullYear()}`;const semesterLabel=s=>{const t=`${s?.type||''} ${s?.name||''}`.toUpperCase();return t.includes('SECOND')||t.includes('2')||s?.name?.includes('الثاني')?'الثاني':'الأول'}
export default function Guidance(){
 const nav=useNavigate();const[params]=useSearchParams();const selectedWorkType=params.get('work_type')||'إرشاد توجيهي';const recordId=params.get('record_id'),weeklyItemId=params.get('weekly_item_id'),weeklyProgramId=params.get('weekly_program_id'),weeklyDate=params.get('date')||today(),weeklyPeriod=params.get('period')||'الحصة الأولى';const[academic,setAcademic]=useState({years:[],semesters:[],grades:[]}),[sections,setSections]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');const[form,setForm]=useState({topic:'',grade_id:params.get('grade_id')||'',section_id:params.get('section_id')||'',session_date:weeklyDate,period:weeklyPeriod,objectives:'',activity_notes:'',counselor_notes:'',school_year_id:params.get('year_id')||'',semester_id:params.get('semester_id')||''})
 useEffect(()=>{(async()=>{try{const a=await listActiveAcademicData();setAcademic(a);try{const p=await currentProfile();if(p?.school_id)setSections(await listSectionsBySchool(p.school_id))}catch{}setForm(f=>({...f,school_year_id:f.school_year_id||a.years?.[0]?.id||'',semester_id:f.semester_id||a.semesters?.find(x=>!f.school_year_id||x.school_year_id===f.school_year_id)?.id||''}));if(recordId){const r=await getGuidanceRecord(recordId);setForm(f=>({...f,...r}))}}catch(e){setError(e.message||'تعذر تحميل الملف.')}finally{setLoading(false)}})()},[recordId])
 const save=async()=>{if(!form.topic.trim()||!form.session_date)return setError('أدخل الموضوع والتاريخ.');if(!form.school_year_id||!form.semester_id)return setError('اختر السنة الدراسية والفصل.');setSaving(true);setError('');try{const payload={topic:form.topic.trim(),grade_id:form.grade_id||null,section_id:form.section_id||null,session_date:form.session_date,period:form.period||'',objectives:form.objectives||'',activity_notes:form.activity_notes||'',counselor_notes:form.counselor_notes||'',school_year_id:form.school_year_id,semester_id:form.semester_id};const r=recordId?await updateGuidanceRecord(recordId,payload):await createGuidanceRecord(payload);if(weeklyItemId)await updateWeeklyItem(weeklyItemId,{work_record_id:r.id,work_route:'/guidance',work_label:'الإرشاد التوجيهي',topic:'الإرشاد التوجيهي',activity_type:'إرشاد توجيهي',grade_id:form.grade_id||null,section_id:form.section_id||null});else if(weeklyProgramId)await createWeeklyItem({weekly_program_id:weeklyProgramId,day_date:weeklyDate,period:weeklyPeriod,day_name:dayName(weeklyDate),activity_type:'إرشاد توجيهي',topic:'الإرشاد التوجيهي',objectives:'',notes:'',status:'COMPLETED',work_record_id:r.id,work_route:'/guidance',work_label:'الإرشاد التوجيهي',grade_id:form.grade_id||null,section_id:form.section_id||null,work_saved_at:new Date().toISOString()});nav('/weekly-program')}catch(e){setError(e.message||'تعذر حفظ الملف.')}finally{setSaving(false)}}
 return <Page title="الإرشاد التوجيهي" sub="إدخال بيانات الإرشاد التوجيهي وربطه بخانة العمل في البرنامج الأسبوعي.">{error&&<ErrorNotice>{error}</ErrorNotice>}{loading?<div className="loading">جارٍ تحميل الملف...</div>:<Card><div className="section-title"><div><h2>{recordId?'تعديل الإرشاد التوجيهي':'بيانات الإرشاد التوجيهي'}</h2><span>السنة والفصل مرتبطان بهذا السجل.</span><div className="selected-work-type">نوع العمل المحدد من البرنامج: <strong>{selectedWorkType}</strong></div></div></div><div className="form-grid two"><Select label="السنة الدراسية" value={form.school_year_id} onChange={e=>setForm({...form,school_year_id:e.target.value})}><option value="">اختر</option>{academic.years.map(y=><option key={y.id} value={y.id}>{yearLabel(y)}</option>)}</Select><Select label="الفصل الدراسي" value={form.semester_id} onChange={e=>setForm({...form,semester_id:e.target.value})}><option value="">اختر</option>{academic.semesters.filter(s=>!form.school_year_id||s.school_year_id===form.school_year_id).map(s=><option key={s.id} value={s.id}>{semesterLabel(s)}</option>)}</Select><Select label="الصف" value={form.grade_id||''} onChange={e=>setForm({...form,grade_id:e.target.value,section_id:''})}><option value="">اختر الصف</option>{academic.grades.map((g,i)=><option key={g.id} value={g.id}>{i+1}</option>)}</Select><Select label="الشعبة" value={form.section_id||''} onChange={e=>setForm({...form,section_id:e.target.value})}><option value="">اختر الشعبة</option>{sections.filter(s=>!form.grade_id||String(s.grade_id)===String(form.grade_id)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><Input label="التاريخ" type="date" value={form.session_date} onChange={e=>setForm({...form,session_date:e.target.value})}/><Input label="الفترة" value={form.period||''} onChange={e=>setForm({...form,period:e.target.value})}/><Input label="الموضوع" value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/></div><div className="form-grid two"><Textarea label="الأهداف" value={form.objectives||''} onChange={e=>setForm({...form,objectives:e.target.value})}/><Textarea label="ملاحظات النشاط" value={form.activity_notes||''} onChange={e=>setForm({...form,activity_notes:e.target.value})}/></div><Textarea label="ملاحظات إضافية" value={form.counselor_notes||''} onChange={e=>setForm({...form,counselor_notes:e.target.value})}/><Button loading={saving} onClick={save}><Save size={16}/> حفظ البيانات</Button></Card>}</Page>
}

