import React,{useEffect,useState}from'react'
import{useNavigate,useSearchParams}from'react-router-dom'
import{Page,Card,Input,Textarea,Button,Select,ErrorNotice}from'../components/UI'
import{currentProfile,listActiveAcademicData,listStudents,createInterviewRecord,getInterviewRecord,updateInterviewRecord,createWeeklyItem,updateWeeklyItem}from'../services/data'
import{ArrowRight,Save}from'lucide-react'

const days=['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس'];const dayName=date=>{const d=new Date(`${date}T00:00:00`);return days[d.getDay()]||''};const pad=n=>String(n).padStart(2,'0')
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
const yearLabel=y=>y?.name||((y?.start_date&&y?.end_date)?`${new Date(y.start_date).getFullYear()}/${new Date(y.end_date).getFullYear()}`:'')
const semesterLabel=s=>{const t=`${s?.type||''} ${s?.name||''}`.toUpperCase();return t.includes('SECOND')||t.includes('2')||s?.name?.includes('الثاني')?'الثاني':'الأول'}

export default function Interviews(){
 const nav=useNavigate();const[params]=useSearchParams();const[profile,setProfile]=useState(null),[academic,setAcademic]=useState({years:[],semesters:[]}),[students,setStudents]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const recordId=params.get('record_id'),weeklyItemId=params.get('weekly_item_id'),weeklyProgramId=params.get('weekly_program_id'),weeklyDate=params.get('date')||today(),weeklyPeriod=params.get('period')||'الحصة الأولى'
 const selectedWorkType=params.get('work_type')||'';
 const[form,setForm]=useState({student_id:'',interview_date:weeklyDate,consultation_type:selectedWorkType==='استشارة'?'استشارة':'مقابلة',topic:'',notes:'',result:'',school_year_id:params.get('year_id')||'',semester_id:params.get('semester_id')||''})
 useEffect(()=>{(async()=>{try{const[p,a,st]=await Promise.all([currentProfile(),listActiveAcademicData(),listStudents()]);setProfile(p);setAcademic(a);setStudents(st);setForm(f=>({...f,school_year_id:f.school_year_id||a.years?.[0]?.id||'',semester_id:f.semester_id||a.semesters?.find(x=>!f.school_year_id||x.school_year_id===f.school_year_id)?.id||''}));if(recordId){const r=await getInterviewRecord(recordId);setForm(f=>({...f,...r}))}}catch(e){setError(e.message||'تعذر تحميل الملف.')}finally{setLoading(false)}})()},[recordId])
 const save=async()=>{if(!form.interview_date||!form.topic.trim())return setError('أدخل التاريخ وموضوع المقابلة.');if(!form.school_year_id||!form.semester_id)return setError('اختر السنة الدراسية والفصل.');setSaving(true);setError('');try{const payload={student_id:form.student_id||null,interview_date:form.interview_date,consultation_type:form.consultation_type,topic:form.topic.trim(),notes:form.notes||'',result:form.result||'',school_year_id:form.school_year_id,semester_id:form.semester_id,grade_id:null,section_id:null};const r=recordId?await updateInterviewRecord(recordId,payload):await createInterviewRecord(payload);if(weeklyItemId)await updateWeeklyItem(weeklyItemId,{work_record_id:r.id,work_route:'/interviews',work_label:'المقابلات والاستشارات',topic:'المقابلات والاستشارات',activity_type:'مقابلات واستشارات'});else if(weeklyProgramId)await createWeeklyItem({weekly_program_id:weeklyProgramId,day_date:weeklyDate,period:weeklyPeriod,day_name:dayName(weeklyDate),activity_type:'مقابلات واستشارات',topic:'المقابلات والاستشارات',objectives:'',notes:'',status:'COMPLETED',work_record_id:r.id,work_route:'/interviews',work_label:'المقابلات والاستشارات',work_saved_at:new Date().toISOString()});nav('/weekly-program')}catch(e){setError(e.message||'تعذر حفظ الملف.')}finally{setSaving(false)}}
 return <Page title="المقابلات والاستشارات" sub="توثيق المقابلات والاستشارات وربطها مباشرة بخانة العمل في البرنامج الأسبوعي.">{error&&<ErrorNotice>{error}</ErrorNotice>}{loading?<div className="loading">جارٍ تحميل الملف...</div>:<Card><div className="section-title"><div><h2>{recordId?'تعديل المقابلات والاستشارات':'بيانات المقابلات والاستشارات'}</h2><span>السنة والفصل مرتبطان بهذا السجل.</span>{selectedWorkType&&<div className="selected-work-type">نوع العمل المحدد من البرنامج: <strong>{selectedWorkType}</strong></div>}</div></div><div className="form-grid two"><Select label="السنة الدراسية" value={form.school_year_id} onChange={e=>setForm({...form,school_year_id:e.target.value})}><option value="">اختر</option>{academic.years.map(y=><option key={y.id} value={y.id}>{yearLabel(y)}</option>)}</Select><Select label="الفصل الدراسي" value={form.semester_id} onChange={e=>setForm({...form,semester_id:e.target.value})}><option value="">اختر</option>{academic.semesters.filter(s=>!form.school_year_id||s.school_year_id===form.school_year_id).map(s=><option key={s.id} value={s.id}>{semesterLabel(s)}</option>)}</Select></div><div className="form-grid two"><Select label="الطالب" value={form.student_id||''} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">اختر الطالب</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</Select><Input label="التاريخ" type="date" value={form.interview_date} onChange={e=>setForm({...form,interview_date:e.target.value})}/><Select label="النوع" value={form.consultation_type||'مقابلة'} onChange={e=>setForm({...form,consultation_type:e.target.value})}><option>مقابلة</option><option>استشارة</option></Select><Input label="الموضوع" value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/></div><div className="form-grid two"><Textarea label="ملخص المقابلة / الملاحظات" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/><Textarea label="النتيجة / التوصيات" value={form.result||''} onChange={e=>setForm({...form,result:e.target.value})}/></div><Button loading={saving} onClick={save}><Save size={16}/> حفظ البيانات</Button></Card>}</Page>
}

