import React,{useEffect,useMemo,useState} from 'react'
import {School,Plus,RefreshCw,Edit3,Save,Trash2} from 'lucide-react'
import {Page,Card,Button,Input,Select,Empty,ErrorNotice} from '../components/UI'
import {currentProfile,listOrganization,createSchool,updateSchool,deleteSchool} from '../services/data'

export default function Schools(){
 const [profile,setProfile]=useState(null),[org,setOrg]=useState({directorates:[],schools:[]}),[form,setForm]=useState({name:'',code:'',directorate_id:''}),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=async()=>{try{setError('');const [p,o]=await Promise.all([currentProfile(),listOrganization()]);setProfile(p);setOrg(o);setForm(f=>({...f,directorate_id:p?.role==='MINISTRY'?f.directorate_id:(p?.directorate_id||f.directorate_id)}))}catch(e){setError(e.message||'تعذر تحميل المدارس.')}}
 useEffect(()=>{load()},[])
 const dirs=useMemo(()=>profile?.role==='MINISTRY'?org.directorates:org.directorates.filter(d=>d.id===profile?.directorate_id),[org,profile])
 const rows=useMemo(()=>profile?.role==='MINISTRY'?org.schools:org.schools.filter(s=>s.directorate_id===profile?.directorate_id),[org,profile])
 const save=async e=>{e.preventDefault();setError('');setNotice('');if(!['MINISTRY','DIRECTORATE'].includes(profile?.role)){setError('هذه الشاشة مخصصة للإدارة.');return}if(!form.name.trim()||!/^[0-9]{8}$/.test(form.code)||!form.directorate_id){setError('اسم المدرسة مطلوب، وكود المدرسة يجب أن يكون 8 أرقام بالضبط.');return}setBusy(true);try{if(editing)await updateSchool(editing,{name:form.name.trim(),code:form.code,directorate_id:form.directorate_id});else await createSchool({name:form.name.trim(),code:form.code,directorate_id:form.directorate_id});setEditing(null);setForm({name:'',code:'',directorate_id:profile?.role==='DIRECTORATE'?profile.directorate_id:''});setNotice(editing?'تم تعديل بيانات المدرسة.':'تمت إضافة المدرسة.');await load()}catch(e){setError(e.message||'تعذر حفظ المدرسة.')}finally{setBusy(false)}}
 const edit=r=>{setEditing(r.id);setForm({name:r.name||'',code:r.code||'',directorate_id:r.directorate_id||''})}
 const remove=async r=>{if(!confirm(`حذف المدرسة «${r.name}»؟`))return;setBusy(true);try{await deleteSchool(r.id);await load();setNotice('تم حذف المدرسة.')}catch(e){setError(e.message||'لا يمكن حذف المدرسة المرتبطة ببيانات.')}finally{setBusy(false)}}
 if(profile&&!['MINISTRY','DIRECTORATE'].includes(profile.role))return <Page title="المدارس"><Card><Empty title="صلاحية غير متاحة" text="إدارة المدارس متاحة لمسؤول الإرشاد ورئيس القسم."/></Card></Page>
 return <Page title="المدارس" sub="شاشة مستقلة لإضافة المدارس وربطها بالمديرية، مع كود من 8 أرقام" actions={<Button variant="secondary" onClick={load}><RefreshCw size={16}/> تحديث</Button>}>
  {error&&<ErrorNotice>{error}</ErrorNotice>}{notice&&<div className="notice">{notice}</div>}
  <div className="org-layout">
   <Card><div className="section-title"><div><h2><Plus size={18}/> {editing?'تعديل مدرسة':'إضافة مدرسة'}</h2><span>الكود إلزامي ومكون من 8 أرقام.</span></div></div><form onSubmit={save}><Input label="اسم المدرسة *" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input label="كود المدرسة *" value={form.code} maxLength={8} inputMode="numeric" onChange={e=>setForm({...form,code:e.target.value.replace(/\D/g,'').slice(0,8)})} placeholder="12345678"/>{profile?.role==='MINISTRY'?<Select label="المديرية *" value={form.directorate_id} onChange={e=>setForm({...form,directorate_id:e.target.value})}><option value="">اختر المديرية</option>{dirs.map(d=><option key={d.id} value={d.id}>{d.name} — {d.code}</option>)}</Select>:<div className="program-meta"><span>المديرية</span><strong>{dirs[0]?.name||'مديريتك'}</strong></div>}<div className="row-actions"><Button loading={busy}><Save size={16}/> {editing?'حفظ التعديل':'إضافة المدرسة'}</Button>{editing&&<Button variant="secondary" type="button" onClick={()=>{setEditing(null);setForm({name:'',code:'',directorate_id:profile?.role==='DIRECTORATE'?profile.directorate_id:''})}}>إلغاء</Button>}</div></form></Card>
   <Card><div className="section-title"><div><h2><School size={18}/> المدارس</h2><span>{rows.length} مدرسة</span></div></div>{rows.length===0?<Empty title="لا توجد مدارس" text="أضف أول مدرسة من النموذج."/>:<div className="table-wrap"><table className="table"><thead><tr><th>المدرسة</th><th>الكود</th><th>المديرية</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td><span className="code-pill">{r.code||'—'}</span></td><td>{r.directorates?.name||dirs.find(d=>d.id===r.directorate_id)?.name||'—'}</td><td className="row-actions"><button className="icon-btn" onClick={()=>edit(r)} title="تعديل"><Edit3 size={16}/></button><button className="icon-btn danger" onClick={()=>remove(r)} title="حذف"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}</Card>
  </div>
 </Page>
}
