import React,{useEffect,useMemo,useState}from'react'
import{Page,Card,Input,Button,Empty,ErrorNotice,Select}from'../components/UI'
import{listStudents,listActiveAcademicData,listSectionsBySchool,currentProfile,createStudent,updateStudent,deleteStudent}from'../services/data'
import{Search,RefreshCw,Plus,Users,Edit3,Trash2,X,Save}from'lucide-react'

const empty={student_code:'',full_name:'',national_id:'',gender:'',date_of_birth:'',residence_area:'',grade_id:'',section_id:'',enrollment_date:'',school_year_id:'',semester_id:'',notes:''}
const yearLabel=y=>y?.name||((y?.start_date&&y?.end_date)?`${new Date(y.start_date).getFullYear()}/${new Date(y.end_date).getFullYear()}`:'')
const semesterLabel=s=>String(s?.name||'').includes('الثاني')||String(s?.type||'').toUpperCase().includes('SECOND')?'الثاني':'الأول'

export default function Students(){
 const[d,setD]=useState([]),[q,setQ]=useState(''),[academic,setAcademic]=useState({years:[],semesters:[],grades:[]}),[sections,setSections]=useState([]),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[showForm,setShowForm]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(empty)
 const load=async()=>{setLoading(true);setError('');try{const[p,a,st]=await Promise.all([currentProfile(),listActiveAcademicData(),listStudents()]);setProfile(p);setAcademic(a);setD(st);const year=a.years?.find(y=>y.is_active)||a.years?.[0];const sem=a.semesters?.find(s=>s.school_year_id===year?.id&&s.is_active)||a.semesters?.find(s=>s.school_year_id===year?.id)||a.semesters?.[0];setForm(f=>({...f,school_year_id:f.school_year_id||year?.id||'',semester_id:f.semester_id||sem?.id||''}))}catch(e){setError(e.message||'تعذر تحميل الطلاب.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(profile?.school_id)listSectionsBySchool(profile.school_id).then(setSections).catch(()=>setSections([]))},[profile?.school_id])
 const x=useMemo(()=>d.filter(s=>`${s.full_name||''} ${s.student_code||''} ${s.national_id||''}`.includes(q)),[d,q])
 const reset=()=>{const year=academic.years?.find(y=>y.is_active)||academic.years?.[0];const sem=academic.semesters?.find(s=>s.school_year_id===year?.id&&s.is_active)||academic.semesters?.find(s=>s.school_year_id===year?.id)||academic.semesters?.[0];setEditing(null);setForm({...empty,school_year_id:year?.id||'',semester_id:sem?.id||''});setError('')}
 const openAdd=()=>{reset();setShowForm(true)}
 const openEdit=s=>{setEditing(s.id);setForm({...empty,...s});setShowForm(true);setError('')}
 const save=async()=>{setError('');if(!form.full_name.trim()||!form.student_code.trim()||!form.grade_id||!form.section_id)return setError('أدخل اسم الطالب ورمزه والصف والشعبة.');if(form.national_id&&!/^\d{9}$/.test(form.national_id))return setError('رقم الهوية يجب أن يكون 9 أرقام بالضبط.');if(!profile?.school_id)return setError('لم يتم ربط حسابك بمدرسة.');setSaving(true);try{const payload={...form,school_id:profile.school_id};if(editing)await updateStudent(editing,payload);else await createStudent(payload);await load();setShowForm(false);reset()}catch(e){setError(e.message||'تعذر حفظ بيانات الطالب.')}finally{setSaving(false)}}
 const remove=async s=>{if(!window.confirm(`هل تريد حذف الطالب «${s.full_name}»؟`))return;try{await deleteStudent(s.id);await load()}catch(e){setError(e.message||'تعذر حذف الطالب.')}}
 return <Page title="الطلاب" sub="إضافة بيانات الطلاب وربطهم بالصف والشعبة لاستخدامهم داخل ملفات الإرشاد." actions={<div className="page-actions"><Button variant="secondary" onClick={load}><RefreshCw size={16}/> تحديث</Button><Button onClick={openAdd}><Plus size={16}/> إضافة بيانات طالب</Button></div>}>
  {error&&<ErrorNotice>{error}</ErrorNotice>}
  {showForm&&<Card><div className="section-title"><div><h2>{editing?'تعديل بيانات الطالب':'إضافة بيانات طالب'}</h2><span>بيانات الطالب والصف الدراسي الحالي.</span></div><Button variant="secondary" onClick={()=>{setShowForm(false);reset()}}><X size={16}/> إغلاق</Button></div>
   <div className="form-grid two"><Input label="رقم الطالب / الرمز" value={form.student_code} onChange={e=>setForm({...form,student_code:e.target.value})}/><Input label="اسم الطالب" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></div>
   <div className="form-grid three"><Input label="رقم الهوية (9 أرقام)" value={form.national_id||''} onChange={e=>setForm({...form,national_id:e.target.value.replace(/\D/g,'').slice(0,9)})} inputMode="numeric" maxLength={9}/><Select label="الجنس" value={form.gender||''} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">اختر</option><option value="ذكر">ذكر</option><option value="أنثى">أنثى</option></Select><Input label="تاريخ الميلاد" type="date" value={form.date_of_birth||''} onChange={e=>setForm({...form,date_of_birth:e.target.value})}/></div>
   <div className="form-grid two"><Select label="السنة الدراسية" value={form.school_year_id||''} onChange={e=>setForm({...form,school_year_id:e.target.value,semester_id:''})}><option value="">اختر</option>{academic.years.map(y=><option key={y.id} value={y.id}>{yearLabel(y)}</option>)}</Select><Select label="الفصل الدراسي" value={form.semester_id||''} onChange={e=>setForm({...form,semester_id:e.target.value})}><option value="">اختر</option>{academic.semesters.filter(s=>!form.school_year_id||s.school_year_id===form.school_year_id).map(s=><option key={s.id} value={s.id}>{semesterLabel(s)}</option>)}</Select></div>
   <div className="form-grid three"><Select label="الصف" value={form.grade_id||''} onChange={e=>setForm({...form,grade_id:e.target.value,section_id:''})}><option value="">اختر الصف</option>{academic.grades.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</Select><Select label="الشعبة" value={form.section_id||''} onChange={e=>setForm({...form,section_id:e.target.value})}><option value="">اختر الشعبة</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><Input label="تاريخ الالتحاق" type="date" value={form.enrollment_date||''} onChange={e=>setForm({...form,enrollment_date:e.target.value})}/></div>
   <div className="form-grid two"><Input label="منطقة السكن" value={form.residence_area||''} onChange={e=>setForm({...form,residence_area:e.target.value})}/><Input label="ملاحظات" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></div>
   <Button loading={saving} onClick={save}><Save size={16}/> {editing?'حفظ التعديل':'حفظ بيانات الطالب'}</Button>
  </Card>}
  <Card><div className="section-title"><div><h2><Users size={18}/> عرض بيانات الطلاب</h2><span>يمكن تعديل أو حذف أي طالب من الجدول.</span></div></div><div className="searchbar"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث باسم الطالب أو رمزه أو رقم الهوية…"/></div>{loading?<div className="loading">جارٍ تحميل الطلاب…</div>:x.length===0?<Empty title="لا يوجد طلاب" text="اضغط «إضافة بيانات طالب» لإضافة أول طالب."/>:<div className="table-wrap"><table className="table"><thead><tr><th>م</th><th>اسم الطالب</th><th>الرمز</th><th>رقم الهوية</th><th>الجنس</th><th>الصف</th><th>الشعبة</th><th>السنة</th><th>الفصل</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>{x.map((s,i)=><tr key={s.id}><td>{i+1}</td><td><strong>{s.full_name}</strong></td><td>{s.student_code||'—'}</td><td>{s.national_id||'—'}</td><td>{s.gender||'—'}</td><td>{s.grades?.name||'—'}</td><td>{s.sections?.name||'—'}</td><td>{s.school_years?.name||'—'}</td><td>{s.semesters?.name||'—'}</td><td><span className="badge">{s.is_active?'نشط':'غير نشط'}</span></td><td><div className="row-actions"><button className="icon-btn" title="تعديل" onClick={()=>openEdit(s)}><Edit3 size={15}/></button><button className="icon-btn danger-icon" title="حذف" onClick={()=>remove(s)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}</Card>
 </Page>
}

