import React,{useEffect,useMemo,useState}from'react'
import {Page,Card,Input,Textarea,Button,Select,Empty,ErrorNotice} from './UI'
import {listRecords,createOwnedRecord,updateRecord,deleteRecord} from '../services/data'

export default function CrudScreen({title,sub,table,fields,select='*',order='created_at',defaults={},preparePayload,transformRows}){
 const [rows,setRows]=useState([]),[form,setForm]=useState(defaults),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const load=()=>{setLoading(true);setError('');listRecords(table,select,order).then(r=>setRows(transformRows?transformRows(r):r)).catch(e=>setError(e.message||'تعذر تحميل البيانات.')).finally(()=>setLoading(false))}
 useEffect(load,[])
 const visible=useMemo(()=>rows,[rows])
 const set=(name,value)=>setForm(f=>({...f,[name]:value}))
 const reset=()=>{setEditing(null);setForm({...defaults})}
 const save=async()=>{setSaving(true);setError('');try{const payload=preparePayload?preparePayload(form):form;if(editing)await updateRecord(table,editing,payload);else await createOwnedRecord(table,payload,{school:!['case_studies','absence_records','lateness_records','dropout_cases','hot_cases'].includes(table)});reset();load()}catch(e){setError(e.message||'تعذر حفظ السجل.')}finally{setSaving(false)}}
 const edit=r=>{setEditing(r.id);const f={...defaults};fields.forEach(x=>{if(x.name)f[x.name]=r[x.name]??x.default??''});setForm(f);window.scrollTo({top:0,behavior:'smooth'})}
 const remove=async id=>{if(!confirm('حذف السجل؟'))return;try{await deleteRecord(table,id);load()}catch(e){setError(e.message||'تعذر الحذف.')}}
 return <Page title={title} sub={sub}><Card><div className="section-title"><div><h2>{editing?'تعديل السجل':'إضافة سجل جديد'}</h2><span>الحفظ يتم مباشرة في Supabase.</span></div>{editing&&<Button variant="secondary" onClick={reset}>إلغاء</Button>}</div><div className="form-grid two">{fields.map(f=>f.render?<React.Fragment key={f.name}>{f.render(form,set)}</React.Fragment>:f.type==='textarea'?<Textarea key={f.name} label={f.label} value={form[f.name]??''} onChange={e=>set(f.name,e.target.value)} placeholder={f.placeholder}/>:f.type==='select'?<Select key={f.name} label={f.label} value={form[f.name]??''} onChange={e=>set(f.name,e.target.value)}><option value="">اختر</option>{(f.options||[]).map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</Select>:<Input key={f.name} label={f.label} type={f.type||'text'} value={form[f.name]??''} onChange={e=>set(f.name,e.target.value)} placeholder={f.placeholder}/>)}</div><Button loading={saving} onClick={save}>{editing?'حفظ التعديل':'حفظ السجل'}</Button></Card>{error&&<ErrorNotice>{error}</ErrorNotice>}<Card><div className="section-title"><div><h2>السجلات المحفوظة</h2><span>{visible.length} سجل</span></div><Button variant="secondary" onClick={load}>تحديث</Button></div>{loading?<div className="loading">جارٍ التحميل…</div>:visible.length===0?<Empty/>:<div className="table-wrap"><table className="table"><thead><tr><th>التاريخ</th>{fields.slice(0,3).map(f=><th key={f.name}>{f.label}</th>)}<th>إجراءات</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.activity_date||r.interview_date||r.consultation_date||r.dropout_date||r.referral_date||r.follow_up_date||r.session_date||r.created_at?.slice(0,10)||'—'}</td>{fields.slice(0,3).map(f=><td key={f.name}>{String(r[f.name]??'—').slice(0,80)}</td>)}<td><div className="item-actions"><button onClick={()=>edit(r)}>تعديل</button><button onClick={()=>remove(r.id)}>حذف</button></div></td></tr>)}</tbody></table></div>}</Card></Page>
}

