import React,{useEffect,useState}from'react';
import{useNavigate}from'react-router-dom';
import{Card,Input,Select,Button,ErrorNotice}from'../components/UI';
import{ensureMyProfile,listDirectorates,listSchoolsByDirectorate,updateMyProfile}from'../services/data';

export default function AccountSetup(){
 const nav=useNavigate();
 const [form,setForm]=useState({full_name:'',phone:'',directorate_id:'',school_id:'',job_title:'مرشد تربوي'});
 const [directorates,setDirectorates]=useState([]),[schools,setSchools]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const[p,d]=await Promise.all([ensureMyProfile(),listDirectorates()]);setDirectorates(d);setForm(f=>({...f,full_name:p?.full_name||f.full_name,phone:p?.phone||'',directorate_id:p?.directorate_id||'',school_id:p?.school_id||'',job_title:p?.job_title||'مرشد تربوي'}));if(p?.directorate_id)setSchools(await listSchoolsByDirectorate(p.directorate_id));}catch(e){setError(e.message||'تعذر تحميل بيانات الحساب.')}finally{setLoading(false)}})()},[]);
 const changeDir=async e=>{const id=e.target.value;setForm(f=>({...f,directorate_id:id,school_id:''}));try{setSchools(await listSchoolsByDirectorate(id))}catch(e){setError(e.message)} };
 const save=async e=>{e.preventDefault();setError('');if(!form.full_name.trim()||!form.directorate_id||!form.school_id){setError('أكمل اسم المرشد والمديرية والمدرسة قبل المتابعة.');return}setSaving(true);try{await updateMyProfile(form);nav('/dashboard',{replace:true})}catch(e){setError(e.message||'تعذر حفظ بيانات الحساب.')}finally{setSaving(false)}};
 if(loading)return <div className="login"><Card><div className="loading">جارٍ تجهيز الحساب…</div></Card></div>;
 return <div className="login"><Card className="setup-card"><div className="login-brand"><div className="brand-mark">🌿</div></div><h1>إكمال بيانات المرشد التربوي</h1><p>هذه البيانات ستظهر في النظام وعند تسجيل الدخول.</p>{error&&<ErrorNotice>{error}</ErrorNotice>}<form onSubmit={save}><Input label="اسم المرشد التربوي *" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} placeholder="مثال: أحمد محمد"/><Input label="رقم الهاتف" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="اختياري"/><Select label="المديرية *" value={form.directorate_id} onChange={changeDir}><option value="">اختر المديرية</option>{directorates.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</Select><Select label="المدرسة *" value={form.school_id} onChange={e=>setForm({...form,school_id:e.target.value})} disabled={!form.directorate_id}><option value="">{form.directorate_id?'اختر المدرسة':'اختر المديرية أولًا'}</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><Input label="المسمى الوظيفي" value={form.job_title} onChange={e=>setForm({...form,job_title:e.target.value})}/><Button loading={saving} style={{width:'100%',marginTop:10}}>حفظ البيانات والدخول للنظام</Button></form></Card></div>
}
