import React,{useEffect,useMemo,useState} from 'react'
import {Mail,Send,Inbox,Plus,RefreshCw,Search,CheckCheck,MessageCircle,ArrowRight,Paperclip} from 'lucide-react'
import {Page,Card,Button,Input,Textarea,Select,Empty,ErrorNotice} from '../components/UI'
import {currentProfile,listMessageRecipients,listMessages,sendMessage,markMessageRead} from '../services/data'

const emptyForm={recipient_id:'',subject:'',body:'',priority:'عادي'}

export default function Messages(){
  const [profile,setProfile]=useState(null),[messages,setMessages]=useState([]),[recipients,setRecipients]=useState([]),[tab,setTab]=useState('inbox'),[selected,setSelected]=useState(null),[form,setForm]=useState(emptyForm),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const load=async()=>{setLoading(true);setError('');try{const p=await currentProfile();setProfile(p);const [m,r]=await Promise.all([listMessages('inbox'),listMessageRecipients()]);setMessages(m);setRecipients(r)}catch(e){setError(e.message||'تعذر تحميل المراسلات.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const visible=useMemo(()=>messages.filter(m=>tab==='inbox'?m.recipient_id===profile?.id:m.sender_id===profile?.id),[messages,tab,profile])
  const unread=messages.filter(m=>m.recipient_id===profile?.id&&!m.read_at).length
  const openMessage=async m=>{setSelected(m);if(m.recipient_id===profile?.id&&!m.read_at){try{await markMessageRead(m.id);setMessages(x=>x.map(row=>row.id===m.id?{...row,read_at:new Date().toISOString()}:row))}catch{}}}
  const submit=async e=>{e.preventDefault();setError('');setNotice('');if(!form.recipient_id||!form.subject.trim()||!form.body.trim()){setError('يرجى اختيار المستلم وكتابة عنوان ونص الرسالة.');return}setSending(true);try{const m=await sendMessage(form);setMessages(x=>[m,...x]);setForm(emptyForm);setTab('sent');setNotice('تم إرسال الرسالة بنجاح.')}catch(e){setError(e.message||'تعذر إرسال الرسالة.')}finally{setSending(false)}}
  return <Page title="المراسلات" sub="مراسلة داخلية رسمية بين مدير الدائرة والمرشدين التربويين" actions={<Button onClick={load} variant="secondary"><RefreshCw size={16}/> تحديث</Button>}>
    <div className="message-tabs">
      <button className={tab==='inbox'?'active':''} onClick={()=>{setTab('inbox');setSelected(null)}}><Inbox size={17}/> الوارد <b>{unread}</b></button>
      <button className={tab==='sent'?'active':''} onClick={()=>{setTab('sent');setSelected(null)}}><Send size={17}/> الصادر</button>
      <button className={tab==='compose'?'active':''} onClick={()=>{setTab('compose');setSelected(null)}}><Plus size={17}/> رسالة جديدة</button>
    </div>
    {error&&<ErrorNotice>{error}</ErrorNotice>}{notice&&<div className="notice">{notice}</div>}
    {tab==='compose'?<Card><div className="section-title"><h2><Send size={18}/> إرسال مراسلة</h2><span>المراسلة تحفظ باسم المرسل وتصل فورًا للمستلم</span></div><form onSubmit={submit}>
      <div className="form-grid two"><Select label="إلى" value={form.recipient_id} onChange={e=>setForm({...form,recipient_id:e.target.value})}><option value="">اختر المستلم</option>{recipients.map(r=><option key={r.id} value={r.id}>{r.full_name} — {r.role==='DIRECTORATE'?'مدير الدائرة':(r.schools?.name||'مرشد تربوي')}</option>)}</Select><Select label="الأولوية" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>عادي</option><option>مهم</option><option>عاجل</option></Select></div>
      <Input label="عنوان الرسالة" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="مثال: متابعة خطة الإرشاد للأسبوع القادم"/>
      <Textarea label="نص الرسالة" value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="اكتب المراسلة هنا..."/>
      <div className="message-compose-footer"><span><Paperclip size={15}/> المرفقات يمكن إضافتها في المرحلة التالية</span><Button loading={sending}><Send size={16}/> إرسال الرسالة</Button></div>
    </form></Card>:<div className="message-layout"><Card className="message-list"><div className="message-list-head"><strong>{tab==='inbox'?'صندوق الوارد':'الرسائل الصادرة'}</strong><span>{visible.length} رسالة</span></div><div className="searchbar"><Search size={16}/><input placeholder="بحث في الرسائل..." onChange={e=>{const q=e.target.value.trim().toLowerCase();setMessages(x=>x) ;document.querySelectorAll('.message-row').forEach(el=>el.style.display=!q||el.innerText.toLowerCase().includes(q)?'flex':'none')}}/></div>{loading?<div className="loading">جارٍ تحميل المراسلات...</div>:visible.length===0?<Empty title="لا توجد مراسلات" text={tab==='inbox'?'ستظهر الرسائل الواردة هنا.':'ستظهر رسائلك المرسلة هنا.'}/>:visible.map(m=><button key={m.id} className={'message-row '+(!m.read_at&&tab==='inbox'?'unread':'')} onClick={()=>openMessage(m)}><div className="message-avatar"><MessageCircle size={16}/></div><div className="message-row-body"><div><strong>{tab==='inbox'?m.sender?.full_name:m.recipient?.full_name}</strong><span>{m.priority}</span></div><b>{m.subject}</b><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString('ar-PS')}</small></div>{!m.read_at&&tab==='inbox'?<i/>:<CheckCheck size={15} className="read-icon"/>}</button>)}</Card><Card className="message-detail">{selected?<><button className="back-message" onClick={()=>setSelected(null)}><ArrowRight size={16}/> العودة للقائمة</button><div className="message-detail-head"><div className="message-avatar large"><MessageCircle size={20}/></div><div><strong>{tab==='inbox'?selected.sender?.full_name:selected.recipient?.full_name}</strong><span>{tab==='inbox'?'رسالة واردة':'رسالة صادرة'} • {new Date(selected.created_at).toLocaleString('ar-PS')}</span></div><em className={selected.priority==='عاجل'?'urgent':''}>{selected.priority}</em></div><hr/><h2>{selected.subject}</h2><p className="message-body">{selected.body}</p></>:<div className="message-placeholder"><Mail size={36}/><strong>اختر رسالة لعرضها</strong><span>يمكنك قراءة المراسلات والاحتفاظ بسجل كامل للتواصل الداخلي.</span></div>}</Card></div>}
  </Page>
}
