import React,{useEffect,useMemo,useState}from'react';
import{useNavigate}from'react-router-dom';
import{Page,Card,Input,Textarea,Button,Select,ErrorNotice}from'../components/UI';
import{listWeeklyPrograms,createWeeklyProgram,createWeeklyItem,updateWeeklyItem,deleteWeeklyItem,currentProfile,listActiveAcademicData}from'../services/data';
import{ChevronLeft,ChevronRight,CalendarDays,ExternalLink,Edit3,Trash2}from'lucide-react';

const days=[['الأحد',0],['الإثنين',1],['الثلاثاء',2],['الأربعاء',3],['الخميس',4]];
const periods=['الحصة الأولى','الحصة الثانية','الحصة الثالثة','الحصة الرابعة','الحصة الخامسة','الحصة السادسة','الحصة السابعة'];
const types=['نشاط إرشادي','مقابلة','استشارة','جلسة جمعي','إرشاد توجيهي','متابعة حالة','اجتماع','حصة/فترة','أخرى'];
const routeFor={
 'جلسة جمعي':'/group-counseling','إرشاد توجيهي':'/guidance','مقابلة':'/interviews','استشارة':'/interviews','متابعة حالة':'/cases','نشاط إرشادي':'/activities','حصة/فترة':'/activities','اجتماع':'/notes','أخرى':'/notes'
};
const iso=d=>d.toISOString().slice(0,10);
const addDays=(start,n)=>{const d=new Date(`${start}T00:00:00`);d.setDate(d.getDate()+n);return iso(d)};
const weekStart=(d=new Date())=>{const x=new Date(d);const day=x.getDay();x.setDate(x.getDate()-(day===0?0:day));return iso(x)};
const emptyForm={day_date:'',period:periods[0],start_time:'',end_time:'',activity_type:'نشاط إرشادي',topic:'',objectives:'',notes:'',status:'PLANNED'};

export default function WeeklyProgram(){
 const nav=useNavigate();const[programs,setPrograms]=useState([]),[profile,setProfile]=useState(null),[academic,setAcademic]=useState({years:[],semesters:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[start,setStart]=useState(weekStart()),[yearId,setYearId]=useState(''),[semesterId,setSemesterId]=useState(''),[form,setForm]=useState({...emptyForm,day_date:weekStart()}),[selected,setSelected]=useState(null);
 const load=async()=>{setLoading(true);setError('');try{const[p,a,u]=await Promise.all([listWeeklyPrograms(),listActiveAcademicData(),currentProfile()]);setPrograms(p||[]);setAcademic(a||{years:[],semesters:[]});setProfile(u||null)}catch(e){setError(e?.message||'تعذر تحميل البرنامج.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);useEffect(()=>{if(academic.years?.[0]&&!yearId)setYearId(academic.years[0].id)},[academic.years,yearId]);useEffect(()=>{if(yearId&&!semesterId){const s=academic.semesters?.find(x=>x.school_year_id===yearId);if(s)setSemesterId(s.id)}},[academic.semesters,yearId,semesterId]);
 const active=useMemo(()=>programs.find(p=>p.week_start===start),[programs,start]);
 const moveWeek=delta=>setStart(addDays(start,delta*7));
 const ensureProgram=async()=>{if(active)return active;if(!yearId||!semesterId)throw new Error('أضف السنة الدراسية والفصل الدراسي من Supabase أولًا.');return createWeeklyProgram({school_year_id:yearId,semester_id:semesterId,week_start:start,week_end:addDays(start,4),title:`برنامج أسبوع ${start}`})};
 const save=async()=>{if(!form.day_date||!form.topic.trim())return setError('أكمل اليوم والموضوع.');setSaving(true);setError('');try{const p=await ensureProgram();const dayName=days.find(([,idx])=>addDays(start,idx)===form.day_date)?.[0]||'';const payload={weekly_program_id:p.id,...form,day_name:dayName,topic:form.topic.trim()};if(selected)await updateWeeklyItem(selected.id,payload);else await createWeeklyItem(payload);setSelected(null);setForm({...emptyForm,day_date:form.day_date});await load()}catch(e){setError(e?.message||'تعذر حفظ البند.')}finally{setSaving(false)}};
 const edit=item=>{setSelected(item);setForm({day_date:item.day_date||start,period:item.period||periods[0],start_time:item.start_time||'',end_time:item.end_time||'',activity_type:item.activity_type||'نشاط إرشادي',topic:item.topic||'',objectives:item.objectives||'',notes:item.notes||'',status:item.status||'PLANNED'});window.scrollTo({top:0,behavior:'smooth'})};
 const remove=async id=>{if(!confirm('حذف هذا البند؟'))return;try{await deleteWeeklyItem(id);await load()}catch(e){setError(e?.message||'تعذر الحذف.')}};
 const goItem=item=>{const route=routeFor[item.activity_type]||'/notes';nav(`${route}?from=weekly&date=${item.day_date}`)};
 return <Page title="البرنامج اليومي / الأسبوعي" sub="أهم شاشة عمل للمرشد: أسبوع كامل، حصص يومية، وكل حصة تفتح شاشة العمل المرتبطة بها." actions={<Button variant="secondary" onClick={()=>window.print()}>طباعة الأسبوع</Button>}>
  {error&&<ErrorNotice>{error}</ErrorNotice>}
  <Card className="weekly-header-card"><div className="week-nav"><Button variant="secondary" onClick={()=>moveWeek(-1)}><ChevronRight size={18}/> الأسبوع السابق</Button><div className="week-current"><CalendarDays size={20}/><div><strong>الأسبوع: {start}</strong><span>{addDays(start,4)}</span></div></div><Button variant="secondary" onClick={()=>moveWeek(1)}>الأسبوع التالي <ChevronLeft size={18}/></Button></div><div className="form-grid four"><Input label="الانتقال إلى أي أسبوع" type="date" value={start} onChange={e=>setStart(weekStart(new Date(`${e.target.value}T00:00:00`)))}/><Select label="السنة الدراسية" value={yearId} onChange={e=>setYearId(e.target.value)}><option value="">اختر</option>{academic.years?.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</Select><Select label="الفصل الدراسي" value={semesterId} onChange={e=>setSemesterId(e.target.value)}><option value="">اختر</option>{academic.semesters?.filter(s=>!yearId||s.school_year_id===yearId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><div className="program-meta"><span>المدرسة</span><strong>{profile?.schools?.name||'غير مرتبطة'}</strong></div></div></Card>
  <Card className="weekly-board"><div className="section-title"><div><h2>الأسبوع كاملًا</h2><span>اضغط على زر الحصة لفتح شاشة العمل المرتبطة، أو استخدم الإضافة لإدخال نشاط جديد.</span></div></div>{loading?<div className="loading">جارٍ تحميل البرنامج…</div>:<div className="week-table-wrap"><div className="week-table"><div className="period-head">الحصص / الأيام</div>{days.map(([day,idx])=><div className="day-head" key={day}><strong>{day}</strong><small>{addDays(start,idx)}</small></div>)}{periods.map(period=><React.Fragment key={period}><div className="period-cell"><strong>{period}</strong></div>{days.map(([day,idx])=>{const date=addDays(start,idx);const item=(active?.weekly_program_items||[]).find(x=>x.day_date===date&&(x.period||'')===period);return <div className="lesson-cell" key={`${period}-${date}`}>{item?<button className="lesson-button filled" onClick={()=>goItem(item)} title="فتح شاشة العمل"><span>{item.topic}</span><small>{item.activity_type}</small><ExternalLink size={14}/></button>:<button className="lesson-button empty-lesson" onClick={()=>{setSelected(null);setForm({...emptyForm,day_date:date,period})}}>+ إضافة</button>}</div>})}</React.Fragment>)}</div></div>}</Card>
  <Card className="weekly-editor"><div className="section-title"><div><h2>{selected?'تعديل بند الحصة':'إضافة بند للحصة'}</h2><span>يمكنك أيضًا فتح الشاشة المتخصصة من زر الحصة بعد الحفظ.</span></div>{selected&&<Button variant="secondary" onClick={()=>{setSelected(null);setForm({...emptyForm,day_date:start})}}>إلغاء</Button>}</div><div className="form-grid four"><Input label="اليوم" type="date" value={form.day_date} onChange={e=>setForm({...form,day_date:e.target.value})} min={start} max={addDays(start,4)}/><Select label="الحصة" value={form.period} onChange={e=>setForm({...form,period:e.target.value})}>{periods.map(x=><option key={x}>{x}</option>)}</Select><Input label="من" type="time" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/><Input label="إلى" type="time" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></div><div className="form-grid three"><Select label="نوع العمل" value={form.activity_type} onChange={e=>setForm({...form,activity_type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</Select><Input label="الموضوع" value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})} placeholder="موضوع الحصة أو اللقاء"/><Select label="الحالة" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="PLANNED">مخطط</option><option value="COMPLETED">منجز</option><option value="NOT_COMPLETED">لم ينفذ</option><option value="CANCELLED">ملغى</option></Select></div><div className="form-grid two"><Textarea label="الأهداف" value={form.objectives} onChange={e=>setForm({...form,objectives:e.target.value})}/><Textarea label="ملاحظات" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><Button loading={saving} onClick={save}>{selected?<><Edit3 size={16}/> حفظ التعديل</>:<>+ إضافة للحصة</>}</Button></Card>
  <Card className="weekly-list"><div className="section-title"><div><h2>تفاصيل الأسبوع المحفوظة</h2><span>{active?.weekly_program_items?.length||0} بند</span></div></div>{(active?.weekly_program_items||[]).length===0?<div className="empty">لا توجد بنود محفوظة لهذا الأسبوع بعد.</div>:<div className="program-detail-list">{[...active.weekly_program_items].sort((a,b)=>`${a.day_date}${a.period}`.localeCompare(`${b.day_date}${b.period}`)).map(item=><div className="program-detail-row" key={item.id}><div><strong>{item.day_name||item.day_date}</strong><span>{item.period} • {item.activity_type}</span></div><strong>{item.topic}</strong><div className="item-actions"><button onClick={()=>goItem(item)}>فتح الشاشة <ExternalLink size={14}/></button><button onClick={()=>edit(item)}>تعديل</button><button onClick={()=>remove(item.id)}><Trash2 size={14}/> حذف</button></div></div>)}</div>}</Card>
 </Page>
}
